name: Ping Bot
on:
  schedule:
    - cron: "*/2 * * * *"  # Run every 2 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Add a 5-minute timeout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run ping script
        env:
          BOT_URL: ${{ secrets.BOT_URL }}  # Use a secret for the bot URL
        run: python ping_bot.py